### ISSUE TITLE
Tables not created

### ISSUE THREAD

**Issue by soyraro** [orchidsoftware/press#12]
### Expected Behavior
Tables migrated after install

### Actual Behavior
Error
1064 You have an error in your SQL syntax; check the manual that corresponds to your M
  ySQL server version for the right syntax to use near 'json not null)

### Steps to Reproduce the Problem

  1. Install Laravel
  2. Set up env file, created auth, setup orchid
  3. Laravel error SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lar_orchid.notifications' doesn't exist  after login
4. php artisan migrate

### Specifications
Uniserver Zero at Windows 10
  - PHP Version: 7.1.1
  - Database Version: 5.6.35

**Comment by tabuna** [comment]
Check system requirements

**Comment by soyraro** [comment]
i see... thanks
