### ISSUE TITLE
Неполная валидация в постах

### ISSUE THREAD

**Issue by ilyaryabchinski** [orchidsoftware/press#20]
Создаем такую запись, не заполняем поле body:

![image](https://user-images.githubusercontent.com/20639767/30786155-6e94a390-a17a-11e7-9616-710a102a4f64.png)

Однако запись все равно добавляется:

![image](https://user-images.githubusercontent.com/20639767/30786161-8540b3e0-a17a-11e7-9530-76f83cd11791.png)

методы rules() и fields() в соответствующем посте:

![image](https://user-images.githubusercontent.com/20639767/30786183-e766ae08-a17a-11e7-8e92-c75923bc3f48.png)

**Comment by tabuna** [comment]
На [демо](https://demo.orchid.software/) результат ожидаемый
