### ISSUE TITLE
After composer update I get "Call to a member function all() on null  "

### ISSUE THREAD

**Issue by andrei-tara** [orchidsoftware/press#26]
In PermissionServiceProvider.php line 74:
                                           
  Call to a member function all() on null  

### Steps to Reproduce the Problem

  1. run composer update

### Specifications
  - PHP Version: 7.1

**Comment by tabuna** [comment]
Hi @andrei-tara . This package is not supported, try to look at the [current](https://github.com/orchidsoftware/platform) repositories.
