### ISSUE TITLE
Добавить LinkPost

### ISSUE THREAD

**Issue by tabuna** [orchidsoftware/press#27]
В платформе метод `linkPost`, был удален

```php
    /**
     * @param string|null $text
     *
     * @return TD
     */
    public function linkPost(string $text = null): self
    {
        return $this->link('platform.entities.type.edit', ['type', 'slug'], $text);
    }
```

Необходимо добавить его с помощью `TD::macro`

**Comment by PSalador** [comment]
не понял как с помощью `TD::macro`
cделал расширением TD
https://github.com/orchidsoftware/press/blob/master/src/Screen/TD.php

**Comment by tabuna** [comment]
Пример расширения колонки через `macro`:
https://github.com/orchidsoftware/platform/issues/785

**Comment by osbre** [comment]
Done in https://github.com/orchidcommunity/press/commit/d53a4a6ebcc44d550fde3f0e8f3f1c08f7e936b6
